version: '3'

services:
    db:
        image: postgres:15
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PUBLIC_PORT}:${POSTGRES_PORT-5432}"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DATABASE}
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #     - 8080:8080            
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "${APP_PORT}:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=${APP_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
            - POSTGRES_HOST=db
            - MAILER_ENABLED=${MAILER_ENABLED:-1}
            - MAILER_HOST=${MAILER_HOST}
            - MAILER_PORT=${MAILER_PORT}
            - MAILER_SECURE=${MAILER_SECURE:-1}
            - MAILER_AUTH_USER=${MAILER_AUTH_USER}
            - MAILER_AUTH_PASSWORD=${MAILER_AUTH_PASSWORD}
            - MAILER_NOREPLY_NAME=${MAILER_NOREPLY_NAME}
            - MAILER_NOREPLY_EMAIL=${MAILER_NOREPLY_EMAIL}
volumes:
    db-data: